### ISSUE TITLE
Can we move this module from the catalog, nothing has been done on this for 7 months

### ISSUE THREAD

**Issue by mjperrins** [cloud-native-toolkit/terraform-gitops-cp-waiops-eventmgr#2]
Can we move this module from the catalog, nothing has been done on this for 7 months @balasgit

**Comment by balasgit** [comment]
Will work on this

**Comment by balasgit** [comment]
Fixed and verified https://github.com/cloud-native-toolkit/software-everywhere/actions/runs/3068392435
